info:
  description: Allows users to add/remove products in their virtual shopping carts
    prior to placing an order.
  title: Mybank Online
  x-cortex-apm:
    datadog:
      monitors:
      - 1234567
  x-cortex-custom-integration-mappings:
  - cart
  x-cortex-custom-metadata:
    cache: redis
    db: mysql
    kafka-topic: cart-additions
    language: Go
    product: Retail Website
    tier: tier_1
  x-cortex-dependencies:
  - description: null
    tag: recommendation_service
  - description: null
    tag: suggestions_service
  x-cortex-git:
    github:
      repository: Mooretex/mybank-online
  x-cortex-groups:
  - lifecycle:generally_available
  - tier:tier_1
  - product:Retail Website
  - language:Go
  x-cortex-k8s:
    deployment: []
  x-cortex-link:
  - name: Confluence
    type: runbook
    url: http://company.atlassian.com/confluence/runbooks
  - name: PagerDuty
    type: incidents
    url: https://your_account.pagerduty.com/services/PH99999
  - name: Datadog
    type: metrics
    url: https://app.datadog.com/your_dashboard?env=prod
  - name: Datadog
    type: metrics
    url: https://app.datadog.com/your_dashboard?env=staging
  x-cortex-oncall:
    pagerduty:
      id: ABCD123
      type: SERVICE
  x-cortex-owners:
  - name: order_management_team
    type: group
  x-cortex-tag: mybank-online
openapi: 3.0.1

